CLASS zcl_5_composite_other DEFINITION
  PUBLIC
  INHERITING FROM zcl_5_composite_base
  FINAL
  CREATE PROTECTED
  GLOBAL FRIENDS zcl_5_composite_base.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_5_composite_other IMPLEMENTATION.
ENDCLASS.
