"! <p class="shorttext synchronized" lang="en">Simple Example Class</p>
CLASS ZCL_SIMPLE_EXAMPLE DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      BEGIN OF FLIGHT_NESTED,
        CARRIER_ID    TYPE /DMO/CARRIER_ID,
        CONNECTION_ID TYPE /DMO/CONNECTION_ID,
        FLIGHT_DATE   TYPE /DMO/FLIGHT_DATE,
        PRICE         TYPE /DMO/FLIGHT_PRICE,
        CURRENCY_CODE TYPE /DMO/CURRENCY_CODE,
        PLANE_TYPE_ID TYPE /DMO/PLANE_TYPE_ID,
        BOOKING       TYPE STANDARD TABLE OF /DMO/BOOKING WITH EMPTY KEY,
      END OF FLIGHT_NESTED.

    TYPES:
      BEGIN OF EXAMPLE_TYPE,
        C1            TYPE I,
        C2            TYPE C LENGTH 10,
        CARRIER_ID    TYPE /DMO/CARRIER_ID,
        CONNECTION_ID TYPE /DMO/CONNECTION_ID,
        FLIGHT        TYPE STANDARD TABLE OF FLIGHT_NESTED WITH EMPTY KEY,
      END OF EXAMPLE_TYPE.
    TYPES:
      EXAMPLE_TABLE_TYPE TYPE STANDARD TABLE OF EXAMPLE_TYPE WITH EMPTY KEY.

    METHODS CONSTRUCTOR
      IMPORTING
        !INPUT1 TYPE STRING
        !INPUT2 TYPE STRING .
    CLASS-METHODS METHOD1
      IMPORTING
        !TABLE TYPE EXAMPLE_TABLE_TYPE .
    CLASS-METHODS METHOD2
      IMPORTING
        !FLIGHT TYPE /DMO/FLIGHT.
    CLASS-METHODS METHOD3
      IMPORTING
        !FLIGHT TYPE REF TO /DMO/FLIGHT.
    CLASS-METHODS METHOD4
      IMPORTING
        !CONNECTION_ID           TYPE /DMO/CONNECTION_ID
      RETURNING
        VALUE(CONNECTION_OUTPUT) TYPE /DMO/CONNECTION_ID.
    CLASS-METHODS GET_SIZE
      RETURNING
        VALUE(SIZE) TYPE I .
    CLASS-METHODS SIZE_OK
      IMPORTING
        !SIZE     TYPE I
      RETURNING
        VALUE(OK) TYPE ABAP_BOOL .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_SIMPLE_EXAMPLE IMPLEMENTATION.


  METHOD CONSTRUCTOR.
  ENDMETHOD.


  METHOD GET_SIZE.
    SIZE = 10.
  ENDMETHOD.


  METHOD METHOD1.
  ENDMETHOD.


  METHOD METHOD2.
  ENDMETHOD.


  METHOD METHOD3.
  ENDMETHOD.


  METHOD METHOD4.
    CONNECTION_OUTPUT = CONNECTION_ID.
  ENDMETHOD.


  METHOD SIZE_OK.
    OK = XSDBOOL( SIZE > 0 ).
  ENDMETHOD.
ENDCLASS.
