"! <p class="shorttext synchronized" lang="en">Tutorial #6 - Planetype A340</p>
CLASS ZCL_OO_TUTORIAL_6_A340 DEFINITION
  PUBLIC
  INHERITING FROM ZCL_OO_TUTORIAL_6_BASE
  FINAL
  CREATE PROTECTED

  GLOBAL FRIENDS ZCL_OO_TUTORIAL_6_BASE.

  PUBLIC SECTION.

    METHODS ZIF_OO_TUTORIAL~CALCULATE_FLIGHT_PRICE
        REDEFINITION .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_OO_TUTORIAL_6_A340 IMPLEMENTATION.


  METHOD ZIF_OO_TUTORIAL~CALCULATE_FLIGHT_PRICE.
    price = SUPER->CALCULATE_FLIGHT_PRICE( ).
    PRICE-PRICE = PRICE-PRICE + 15.
  ENDMETHOD.
ENDCLASS.
