"! <p class="shorttext synchronized" lang="en">OO Tutorial Base Interface</p>
INTERFACE ZIF_OO_TUTORIAL
  PUBLIC .


  TYPES:
    BEGIN OF COST,
      PRICE    TYPE /DMO/FLIGHT_PRICE,
      CURRENCY TYPE /DMO/CURRENCY_CODE,
    END OF COST .

  METHODS GET_FLIGHT_DETAILS
    RETURNING
      VALUE(FLIGHT) TYPE /DMO/FLIGHT .
  METHODS CALCULATE_FLIGHT_PRICE
    RETURNING
      VALUE(PRICE) TYPE COST .
ENDINTERFACE.
